import { CountryData } from '@core/models/ddx-country.model';
import { TimeZone } from '@core/models';

export const CONSTANTS = {
  SERVER_URL: 'https://api.didex.com/',
  MOCK_SERVER_URL: 'https://devapi.didex.com/',
  PHONE_VERIFICATION_CODE_LENGTH: 6,
  PAGINATION_LIMIT_BIG: 150,
  PAGINATION_LIMIT: 25,
  PAGINATION_LIMIT_SMALL: 10,
  RECAPTCHA_SITE_KEY: '6LcgguIUAAAAAE1GXYfJd7z-uEah67Dd9kTgWcpz',
};

export const COUNTRIES: CountryData[] = [
  // {
  //   code: 'AC',
  //   emoji: '🇦🇨',
  //   name: 'Ascension Island',
  //   phoneCode: '247',
  //   unicode: 'U+1F1E6 U+1F1E8',
  // },
  {
    code: 'AD',
    emoji: '🇦🇩',
    name: 'Andorra',
    phoneCode: '376',
    unicode: 'U+1F1E6 U+1F1E9',
  },
  {
    code: 'AE',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    phoneCode: '971',
    unicode: 'U+1F1E6 U+1F1EA',
  },
  {
    code: 'AF',
    emoji: '🇦🇫',
    name: 'Afghanistan',
    phoneCode: '93',
    unicode: 'U+1F1E6 U+1F1EB',
  },
  {
    code: 'AG',
    emoji: '🇦🇬',
    name: 'Antigua & Barbuda',
    phoneCode: '1-268',
    unicode: 'U+1F1E6 U+1F1EC',
  },
  {
    code: 'AI',
    emoji: '🇦🇮',
    name: 'Anguilla',
    phoneCode: '1-264',
    unicode: 'U+1F1E6 U+1F1EE',
  },
  {
    code: 'AL',
    emoji: '🇦🇱',
    name: 'Albania',
    phoneCode: '355',
    unicode: 'U+1F1E6 U+1F1F1',
  },
  {
    code: 'AM',
    emoji: '🇦🇲',
    name: 'Armenia',
    phoneCode: '374',
    unicode: 'U+1F1E6 U+1F1F2',
  },
  {
    code: 'AO',
    emoji: '🇦🇴',
    name: 'Angola',
    phoneCode: '244',
    unicode: 'U+1F1E6 U+1F1F4',
  },
  {
    code: 'AR',
    emoji: '🇦🇷',
    name: 'Argentina',
    phoneCode: '54',
    unicode: 'U+1F1E6 U+1F1F7',
  },
  {
    code: 'AS',
    emoji: '🇦🇸',
    name: 'American Samoa',
    phoneCode: '1-684',
    unicode: 'U+1F1E6 U+1F1F8',
  },
  {
    code: 'AT',
    emoji: '🇦🇹',
    name: 'Austria',
    phoneCode: '43',
    unicode: 'U+1F1E6 U+1F1F9',
  },
  {
    code: 'AU',
    emoji: '🇦🇺',
    name: 'Australia',
    phoneCode: '61',
    unicode: 'U+1F1E6 U+1F1FA',
  },
  {
    code: 'AW',
    emoji: '🇦🇼',
    name: 'Aruba',
    phoneCode: '297',
    unicode: 'U+1F1E6 U+1F1FC',
  },
  {
    code: 'AX',
    emoji: '🇦🇽',
    name: 'Åland Islands',
    phoneCode: '358-18',
    unicode: 'U+1F1E6 U+1F1FD',
  },
  {
    code: 'AZ',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
    phoneCode: '994',
    unicode: 'U+1F1E6 U+1F1FF',
  },
  {
    code: 'BA',
    emoji: '🇧🇦',
    name: 'Bosnia & Herzegovina',
    phoneCode: '387',
    unicode: 'U+1F1E7 U+1F1E6',
  },
  {
    code: 'BB',
    emoji: '🇧🇧',
    name: 'Barbados',
    phoneCode: '1-246',
    unicode: 'U+1F1E7 U+1F1E7',
  },
  {
    code: 'BD',
    emoji: '🇧🇩',
    name: 'Bangladesh',
    phoneCode: '880',
    unicode: 'U+1F1E7 U+1F1E9',
  },
  {
    code: 'BE',
    emoji: '🇧🇪',
    name: 'Belgium',
    phoneCode: '32',
    unicode: 'U+1F1E7 U+1F1EA',
  },
  {
    code: 'BF',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
    phoneCode: '226',
    unicode: 'U+1F1E7 U+1F1EB',
  },
  {
    code: 'BG',
    emoji: '🇧🇬',
    name: 'Bulgaria',
    phoneCode: '359',
    unicode: 'U+1F1E7 U+1F1EC',
  },
  {
    code: 'BH',
    emoji: '🇧🇭',
    name: 'Bahrain',
    phoneCode: '973',
    unicode: 'U+1F1E7 U+1F1ED',
  },
  {
    code: 'BI',
    emoji: '🇧🇮',
    name: 'Burundi',
    phoneCode: '257',
    unicode: 'U+1F1E7 U+1F1EE',
  },
  {
    code: 'BJ',
    emoji: '🇧🇯',
    name: 'Benin',
    phoneCode: '229',
    unicode: 'U+1F1E7 U+1F1EF',
  },
  {
    code: 'BL',
    emoji: '🇧🇱',
    name: 'St. Barthélemy',
    phoneCode: '590',
    unicode: 'U+1F1E7 U+1F1F1',
  },
  {
    code: 'BM',
    emoji: '🇧🇲',
    name: 'Bermuda',
    phoneCode: '1-441',
    unicode: 'U+1F1E7 U+1F1F2',
  },
  {
    code: 'BN',
    emoji: '🇧🇳',
    name: 'Brunei',
    phoneCode: '673',
    unicode: 'U+1F1E7 U+1F1F3',
  },
  {
    code: 'BO',
    emoji: '🇧🇴',
    name: 'Bolivia',
    phoneCode: '591',
    unicode: 'U+1F1E7 U+1F1F4',
  },
  {
    code: 'BQ',
    emoji: '🇧🇶',
    name: 'Caribbean Netherlands',
    phoneCode: '599',
    unicode: 'U+1F1E7 U+1F1F6',
  },
  {
    code: 'BR',
    emoji: '🇧🇷',
    name: 'Brazil',
    phoneCode: '55',
    unicode: 'U+1F1E7 U+1F1F7',
  },
  {
    code: 'BS',
    emoji: '🇧🇸',
    name: 'Bahamas',
    phoneCode: '1-242',
    unicode: 'U+1F1E7 U+1F1F8',
  },
  {
    code: 'BT',
    emoji: '🇧🇹',
    name: 'Bhutan',
    phoneCode: '975',
    unicode: 'U+1F1E7 U+1F1F9',
  },
  {
    code: 'BW',
    emoji: '🇧🇼',
    name: 'Botswana',
    phoneCode: '267',
    unicode: 'U+1F1E7 U+1F1FC',
  },
  {
    code: 'BY',
    emoji: '🇧🇾',
    name: 'Belarus',
    phoneCode: '375',
    unicode: 'U+1F1E7 U+1F1FE',
  },
  {
    code: 'BZ',
    emoji: '🇧🇿',
    name: 'Belize',
    phoneCode: '501',
    unicode: 'U+1F1E7 U+1F1FF',
  },
  {
    code: 'CA',
    emoji: '🇨🇦',
    name: 'Canada',
    phoneCode: '1',
    unicode: 'U+1F1E8 U+1F1E6',
  },
  {
    code: 'CC',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    phoneCode: '61',
    unicode: 'U+1F1E8 U+1F1E8',
  },
  {
    code: 'CD',
    emoji: '🇨🇩',
    name: 'Congo - Kinshasa',
    phoneCode: '243',
    unicode: 'U+1F1E8 U+1F1E9',
  },
  {
    code: 'CF',
    emoji: '🇨🇫',
    name: 'Central African Republic',
    phoneCode: '236',
    unicode: 'U+1F1E8 U+1F1EB',
  },
  {
    code: 'CG',
    emoji: '🇨🇬',
    name: 'Congo - Brazzaville',
    phoneCode: '242',
    unicode: 'U+1F1E8 U+1F1EC',
  },
  {
    code: 'CH',
    emoji: '🇨🇭',
    name: 'Switzerland',
    phoneCode: '41',
    unicode: 'U+1F1E8 U+1F1ED',
  },
  {
    code: 'CI',
    emoji: '🇨🇮',
    name: 'Côte d’Ivoire',
    phoneCode: '225',
    unicode: 'U+1F1E8 U+1F1EE',
  },
  {
    code: 'CK',
    emoji: '🇨🇰',
    name: 'Cook Islands',
    phoneCode: '682',
    unicode: 'U+1F1E8 U+1F1F0',
  },
  {
    code: 'CL',
    emoji: '🇨🇱',
    name: 'Chile',
    phoneCode: '56',
    unicode: 'U+1F1E8 U+1F1F1',
  },
  {
    code: 'CM',
    emoji: '🇨🇲',
    name: 'Cameroon',
    phoneCode: '237',
    unicode: 'U+1F1E8 U+1F1F2',
  },
  {
    code: 'CN',
    emoji: '🇨🇳',
    name: 'China',
    phoneCode: '86',
    unicode: 'U+1F1E8 U+1F1F3',
  },
  {
    code: 'CO',
    emoji: '🇨🇴',
    name: 'Colombia',
    phoneCode: '57',
    unicode: 'U+1F1E8 U+1F1F4',
  },
  {
    code: 'CR',
    emoji: '🇨🇷',
    name: 'Costa Rica',
    phoneCode: '506',
    unicode: 'U+1F1E8 U+1F1F7',
  },
  {
    code: 'CU',
    emoji: '🇨🇺',
    name: 'Cuba',
    phoneCode: '53',
    unicode: 'U+1F1E8 U+1F1FA',
  },
  {
    code: 'CV',
    emoji: '🇨🇻',
    name: 'Cape Verde',
    phoneCode: '238',
    unicode: 'U+1F1E8 U+1F1FB',
  },
  {
    code: 'CW',
    emoji: '🇨🇼',
    name: 'Curaçao',
    phoneCode: '599',
    unicode: 'U+1F1E8 U+1F1FC',
  },
  {
    code: 'CX',
    emoji: '🇨🇽',
    name: 'Christmas Island',
    phoneCode: '61',
    unicode: 'U+1F1E8 U+1F1FD',
  },
  {
    code: 'CY',
    emoji: '🇨🇾',
    name: 'Cyprus',
    phoneCode: '357',
    unicode: 'U+1F1E8 U+1F1FE',
  },
  {
    code: 'CZ',
    emoji: '🇨🇿',
    name: 'Czechia',
    phoneCode: '420',
    unicode: 'U+1F1E8 U+1F1FF',
  },
  {
    code: 'DE',
    emoji: '🇩🇪',
    name: 'Germany',
    phoneCode: '49',
    unicode: 'U+1F1E9 U+1F1EA',
  },
  {
    code: 'DG',
    emoji: '🇩🇬',
    name: 'Diego Garcia',
    phoneCode: '246',
    unicode: 'U+1F1E9 U+1F1EC',
  },
  {
    code: 'DJ',
    emoji: '🇩🇯',
    name: 'Djibouti',
    phoneCode: '253',
    unicode: 'U+1F1E9 U+1F1EF',
  },
  {
    code: 'DK',
    emoji: '🇩🇰',
    name: 'Denmark',
    phoneCode: '45',
    unicode: 'U+1F1E9 U+1F1F0',
  },
  {
    code: 'DM',
    emoji: '🇩🇲',
    name: 'Dominica',
    phoneCode: '1-767',
    unicode: 'U+1F1E9 U+1F1F2',
  },
  {
    code: 'DO',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    phoneCode: '1-809 and 1-829',
    unicode: 'U+1F1E9 U+1F1F4',
  },
  {
    code: 'DZ',
    emoji: '🇩🇿',
    name: 'Algeria',
    phoneCode: '213',
    unicode: 'U+1F1E9 U+1F1FF',
  },
  {
    code: 'EC',
    emoji: '🇪🇨',
    name: 'Ecuador',
    phoneCode: '593',
    unicode: 'U+1F1EA U+1F1E8',
  },
  {
    code: 'EE',
    emoji: '🇪🇪',
    name: 'Estonia',
    phoneCode: '372',
    unicode: 'U+1F1EA U+1F1EA',
  },
  {
    code: 'EG',
    emoji: '🇪🇬',
    name: 'Egypt',
    phoneCode: '20',
    unicode: 'U+1F1EA U+1F1EC',
  },
  {
    code: 'EH',
    emoji: '🇪🇭',
    name: 'Western Sahara',
    phoneCode: '212',
    unicode: 'U+1F1EA U+1F1ED',
  },
  {
    code: 'ER',
    emoji: '🇪🇷',
    name: 'Eritrea',
    phoneCode: '291',
    unicode: 'U+1F1EA U+1F1F7',
  },
  {
    code: 'ES',
    emoji: '🇪🇸',
    name: 'Spain',
    phoneCode: '34',
    unicode: 'U+1F1EA U+1F1F8',
  },
  {
    code: 'ET',
    emoji: '🇪🇹',
    name: 'Ethiopia',
    phoneCode: '251',
    unicode: 'U+1F1EA U+1F1F9',
  },
  {
    code: 'FI',
    emoji: '🇫🇮',
    name: 'Finland',
    phoneCode: '358',
    unicode: 'U+1F1EB U+1F1EE',
  },
  {
    code: 'FJ',
    emoji: '🇫🇯',
    name: 'Fiji',
    phoneCode: '679',
    unicode: 'U+1F1EB U+1F1EF',
  },
  {
    code: 'FK',
    emoji: '🇫🇰',
    name: 'Falkland Islands',
    phoneCode: '500',
    unicode: 'U+1F1EB U+1F1F0',
  },
  {
    code: 'FM',
    emoji: '🇫🇲',
    name: 'Micronesia',
    phoneCode: '691',
    unicode: 'U+1F1EB U+1F1F2',
  },
  {
    code: 'FO',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
    phoneCode: '298',
    unicode: 'U+1F1EB U+1F1F4',
  },
  {
    code: 'FR',
    emoji: '🇫🇷',
    name: 'France',
    phoneCode: '33',
    unicode: 'U+1F1EB U+1F1F7',
  },
  {
    code: 'GA',
    emoji: '🇬🇦',
    name: 'Gabon',
    phoneCode: '241',
    unicode: 'U+1F1EC U+1F1E6',
  },
  {
    code: 'GB',
    emoji: '🇬🇧',
    name: 'United Kingdom',
    phoneCode: '44',
    unicode: 'U+1F1EC U+1F1E7',
  },
  {
    code: 'GD',
    emoji: '🇬🇩',
    name: 'Grenada',
    phoneCode: '1-473',
    unicode: 'U+1F1EC U+1F1E9',
  },
  {
    code: 'GE',
    emoji: '🇬🇪',
    name: 'Georgia',
    phoneCode: '995',
    unicode: 'U+1F1EC U+1F1EA',
  },
  {
    code: 'GF',
    emoji: '🇬🇫',
    name: 'French Guiana',
    phoneCode: '594',
    unicode: 'U+1F1EC U+1F1EB',
  },
  {
    code: 'GG',
    emoji: '🇬🇬',
    name: 'Guernsey',
    phoneCode: '44-1481',
    unicode: 'U+1F1EC U+1F1EC',
  },
  {
    code: 'GH',
    emoji: '🇬🇭',
    name: 'Ghana',
    phoneCode: '233',
    unicode: 'U+1F1EC U+1F1ED',
  },
  {
    code: 'GI',
    emoji: '🇬🇮',
    name: 'Gibraltar',
    phoneCode: '350',
    unicode: 'U+1F1EC U+1F1EE',
  },
  {
    code: 'GL',
    emoji: '🇬🇱',
    name: 'Greenland',
    phoneCode: '299',
    unicode: 'U+1F1EC U+1F1F1',
  },
  {
    code: 'GM',
    emoji: '🇬🇲',
    name: 'Gambia',
    phoneCode: '220',
    unicode: 'U+1F1EC U+1F1F2',
  },
  {
    code: 'GN',
    emoji: '🇬🇳',
    name: 'Guinea',
    phoneCode: '224',
    unicode: 'U+1F1EC U+1F1F3',
  },
  {
    code: 'GP',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
    phoneCode: '590',
    unicode: 'U+1F1EC U+1F1F5',
  },
  {
    code: 'GQ',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    phoneCode: '240',
    unicode: 'U+1F1EC U+1F1F6',
  },
  {
    code: 'GR',
    emoji: '🇬🇷',
    name: 'Greece',
    phoneCode: '30',
    unicode: 'U+1F1EC U+1F1F7',
  },
  {
    code: 'GT',
    emoji: '🇬🇹',
    name: 'Guatemala',
    phoneCode: '502',
    unicode: 'U+1F1EC U+1F1F9',
  },
  {
    code: 'GU',
    emoji: '🇬🇺',
    name: 'Guam',
    phoneCode: '1-671',
    unicode: 'U+1F1EC U+1F1FA',
  },
  {
    code: 'GW',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
    phoneCode: '245',
    unicode: 'U+1F1EC U+1F1FC',
  },
  {
    code: 'GY',
    emoji: '🇬🇾',
    name: 'Guyana',
    phoneCode: '592',
    unicode: 'U+1F1EC U+1F1FE',
  },
  {
    code: 'HK',
    emoji: '🇭🇰',
    name: 'Hong Kong SAR China',
    phoneCode: '852',
    unicode: 'U+1F1ED U+1F1F0',
  },
  {
    code: 'HM',
    emoji: '🇭🇲',
    name: 'Heard & McDonald Islands',
    phoneCode: ' ',
    unicode: 'U+1F1ED U+1F1F2',
  },
  {
    code: 'HN',
    emoji: '🇭🇳',
    name: 'Honduras',
    phoneCode: '504',
    unicode: 'U+1F1ED U+1F1F3',
  },
  {
    code: 'HR',
    emoji: '🇭🇷',
    name: 'Croatia',
    phoneCode: '385',
    unicode: 'U+1F1ED U+1F1F7',
  },
  {
    code: 'HT',
    emoji: '🇭🇹',
    name: 'Haiti',
    phoneCode: '509',
    unicode: 'U+1F1ED U+1F1F9',
  },
  {
    code: 'HU',
    emoji: '🇭🇺',
    name: 'Hungary',
    phoneCode: '36',
    unicode: 'U+1F1ED U+1F1FA',
  },
  {
    code: 'IC',
    emoji: '🇮🇨',
    name: 'Canary Islands',
    phoneCode: '34',
    unicode: 'U+1F1EE U+1F1E8',
  },
  {
    code: 'ID',
    emoji: '🇮🇩',
    name: 'Indonesia',
    phoneCode: '62',
    unicode: 'U+1F1EE U+1F1E9',
  },
  {
    code: 'IE',
    emoji: '🇮🇪',
    name: 'Ireland',
    phoneCode: '353',
    unicode: 'U+1F1EE U+1F1EA',
  },
  {
    code: 'IL',
    emoji: '🇮🇱',
    name: 'Israel',
    phoneCode: '972',
    unicode: 'U+1F1EE U+1F1F1',
  },
  {
    code: 'IM',
    emoji: '🇮🇲',
    name: 'Isle of Man',
    phoneCode: '44-1624',
    unicode: 'U+1F1EE U+1F1F2',
  },
  {
    code: 'IN',
    emoji: '🇮🇳',
    name: 'India',
    phoneCode: '91',
    unicode: 'U+1F1EE U+1F1F3',
  },
  {
    code: 'IO',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    phoneCode: '246',
    unicode: 'U+1F1EE U+1F1F4',
  },
  {
    code: 'IQ',
    emoji: '🇮🇶',
    name: 'Iraq',
    phoneCode: '964',
    unicode: 'U+1F1EE U+1F1F6',
  },
  {
    code: 'IR',
    emoji: '🇮🇷',
    name: 'Iran',
    phoneCode: '98',
    unicode: 'U+1F1EE U+1F1F7',
  },
  {
    code: 'IS',
    emoji: '🇮🇸',
    name: 'Iceland',
    phoneCode: '354',
    unicode: 'U+1F1EE U+1F1F8',
  },
  {
    code: 'IT',
    emoji: '🇮🇹',
    name: 'Italy',
    phoneCode: '39',
    unicode: 'U+1F1EE U+1F1F9',
  },
  {
    code: 'JE',
    emoji: '🇯🇪',
    name: 'Jersey',
    phoneCode: '44-1534',
    unicode: 'U+1F1EF U+1F1EA',
  },
  {
    code: 'JM',
    emoji: '🇯🇲',
    name: 'Jamaica',
    phoneCode: '1-876',
    unicode: 'U+1F1EF U+1F1F2',
  },
  {
    code: 'JO',
    emoji: '🇯🇴',
    name: 'Jordan',
    phoneCode: '962',
    unicode: 'U+1F1EF U+1F1F4',
  },
  {
    code: 'JP',
    emoji: '🇯🇵',
    name: 'Japan',
    phoneCode: '81',
    unicode: 'U+1F1EF U+1F1F5',
  },
  {
    code: 'KE',
    emoji: '🇰🇪',
    name: 'Kenya',
    phoneCode: '254',
    unicode: 'U+1F1F0 U+1F1EA',
  },
  {
    code: 'KG',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
    phoneCode: '996',
    unicode: 'U+1F1F0 U+1F1EC',
  },
  {
    code: 'KH',
    emoji: '🇰🇭',
    name: 'Cambodia',
    phoneCode: '855',
    unicode: 'U+1F1F0 U+1F1ED',
  },
  {
    code: 'KI',
    emoji: '🇰🇮',
    name: 'Kiribati',
    phoneCode: '686',
    unicode: 'U+1F1F0 U+1F1EE',
  },
  {
    code: 'KM',
    emoji: '🇰🇲',
    name: 'Comoros',
    phoneCode: '269',
    unicode: 'U+1F1F0 U+1F1F2',
  },
  {
    code: 'KN',
    emoji: '🇰🇳',
    name: 'St. Kitts & Nevis',
    phoneCode: '1-869',
    unicode: 'U+1F1F0 U+1F1F3',
  },
  {
    code: 'KP',
    emoji: '🇰🇵',
    name: 'North Korea',
    phoneCode: '850',
    unicode: 'U+1F1F0 U+1F1F5',
  },
  {
    code: 'KR',
    emoji: '🇰🇷',
    name: 'South Korea',
    phoneCode: '82',
    unicode: 'U+1F1F0 U+1F1F7',
  },
  {
    code: 'KW',
    emoji: '🇰🇼',
    name: 'Kuwait',
    phoneCode: '965',
    unicode: 'U+1F1F0 U+1F1FC',
  },
  {
    code: 'KY',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
    phoneCode: '1-345',
    unicode: 'U+1F1F0 U+1F1FE',
  },
  {
    code: 'KZ',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
    phoneCode: '7',
    unicode: 'U+1F1F0 U+1F1FF',
  },
  {
    code: 'LA',
    emoji: '🇱🇦',
    name: 'Laos',
    phoneCode: '856',
    unicode: 'U+1F1F1 U+1F1E6',
  },
  {
    code: 'LB',
    emoji: '🇱🇧',
    name: 'Lebanon',
    phoneCode: '961',
    unicode: 'U+1F1F1 U+1F1E7',
  },
  {
    code: 'LC',
    emoji: '🇱🇨',
    name: 'St. Lucia',
    phoneCode: '1-758',
    unicode: 'U+1F1F1 U+1F1E8',
  },
  {
    code: 'LI',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
    phoneCode: '423',
    unicode: 'U+1F1F1 U+1F1EE',
  },
  {
    code: 'LK',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
    phoneCode: '94',
    unicode: 'U+1F1F1 U+1F1F0',
  },
  {
    code: 'LR',
    emoji: '🇱🇷',
    name: 'Liberia',
    phoneCode: '231',
    unicode: 'U+1F1F1 U+1F1F7',
  },
  {
    code: 'LS',
    emoji: '🇱🇸',
    name: 'Lesotho',
    phoneCode: '266',
    unicode: 'U+1F1F1 U+1F1F8',
  },
  {
    code: 'LT',
    emoji: '🇱🇹',
    name: 'Lithuania',
    phoneCode: '370',
    unicode: 'U+1F1F1 U+1F1F9',
  },
  {
    code: 'LU',
    emoji: '🇱🇺',
    name: 'Luxembourg',
    phoneCode: '352',
    unicode: 'U+1F1F1 U+1F1FA',
  },
  {
    code: 'LV',
    emoji: '🇱🇻',
    name: 'Latvia',
    phoneCode: '371',
    unicode: 'U+1F1F1 U+1F1FB',
  },
  {
    code: 'LY',
    emoji: '🇱🇾',
    name: 'Libya',
    phoneCode: '218',
    unicode: 'U+1F1F1 U+1F1FE',
  },
  {
    code: 'MA',
    emoji: '🇲🇦',
    name: 'Morocco',
    phoneCode: '212',
    unicode: 'U+1F1F2 U+1F1E6',
  },
  {
    code: 'MC',
    emoji: '🇲🇨',
    name: 'Monaco',
    phoneCode: '377',
    unicode: 'U+1F1F2 U+1F1E8',
  },
  {
    code: 'MD',
    emoji: '🇲🇩',
    name: 'Moldova',
    phoneCode: '373',
    unicode: 'U+1F1F2 U+1F1E9',
  },
  {
    code: 'ME',
    emoji: '🇲🇪',
    name: 'Montenegro',
    phoneCode: '382',
    unicode: 'U+1F1F2 U+1F1EA',
  },
  {
    code: 'MF',
    emoji: '🇲🇫',
    name: 'St. Martin',
    phoneCode: '590',
    unicode: 'U+1F1F2 U+1F1EB',
  },
  {
    code: 'MG',
    emoji: '🇲🇬',
    name: 'Madagascar',
    phoneCode: '261',
    unicode: 'U+1F1F2 U+1F1EC',
  },
  {
    code: 'MH',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    phoneCode: '692',
    unicode: 'U+1F1F2 U+1F1ED',
  },
  {
    code: 'MK',
    emoji: '🇲🇰',
    name: 'Macedonia',
    phoneCode: '389',
    unicode: 'U+1F1F2 U+1F1F0',
  },
  {
    code: 'ML',
    emoji: '🇲🇱',
    name: 'Mali',
    phoneCode: '223',
    unicode: 'U+1F1F2 U+1F1F1',
  },
  {
    code: 'MM',
    emoji: '🇲🇲',
    name: 'Myanmar (Burma)',
    phoneCode: '95',
    unicode: 'U+1F1F2 U+1F1F2',
  },
  {
    code: 'MN',
    emoji: '🇲🇳',
    name: 'Mongolia',
    phoneCode: '976',
    unicode: 'U+1F1F2 U+1F1F3',
  },
  {
    code: 'MO',
    emoji: '🇲🇴',
    name: 'Macau SAR China',
    phoneCode: '853',
    unicode: 'U+1F1F2 U+1F1F4',
  },
  {
    code: 'MP',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    phoneCode: '1-670',
    unicode: 'U+1F1F2 U+1F1F5',
  },
  {
    code: 'MQ',
    emoji: '🇲🇶',
    name: 'Martinique',
    phoneCode: '596',
    unicode: 'U+1F1F2 U+1F1F6',
  },
  {
    code: 'MR',
    emoji: '🇲🇷',
    name: 'Mauritania',
    phoneCode: '222',
    unicode: 'U+1F1F2 U+1F1F7',
  },
  {
    code: 'MS',
    emoji: '🇲🇸',
    name: 'Montserrat',
    phoneCode: '1-664',
    unicode: 'U+1F1F2 U+1F1F8',
  },
  {
    code: 'MT',
    emoji: '🇲🇹',
    name: 'Malta',
    phoneCode: '356',
    unicode: 'U+1F1F2 U+1F1F9',
  },
  {
    code: 'MU',
    emoji: '🇲🇺',
    name: 'Mauritius',
    phoneCode: '230',
    unicode: 'U+1F1F2 U+1F1FA',
  },
  {
    code: 'MV',
    emoji: '🇲🇻',
    name: 'Maldives',
    phoneCode: '960',
    unicode: 'U+1F1F2 U+1F1FB',
  },
  {
    code: 'MW',
    emoji: '🇲🇼',
    name: 'Malawi',
    phoneCode: '265',
    unicode: 'U+1F1F2 U+1F1FC',
  },
  {
    code: 'MX',
    emoji: '🇲🇽',
    name: 'Mexico',
    phoneCode: '52',
    unicode: 'U+1F1F2 U+1F1FD',
  },
  {
    code: 'MY',
    emoji: '🇲🇾',
    name: 'Malaysia',
    phoneCode: '60',
    unicode: 'U+1F1F2 U+1F1FE',
  },
  {
    code: 'MZ',
    emoji: '🇲🇿',
    name: 'Mozambique',
    phoneCode: '258',
    unicode: 'U+1F1F2 U+1F1FF',
  },
  {
    code: 'NA',
    emoji: '🇳🇦',
    name: 'Namibia',
    phoneCode: '264',
    unicode: 'U+1F1F3 U+1F1E6',
  },
  {
    code: 'NC',
    emoji: '🇳🇨',
    name: 'New Caledonia',
    phoneCode: '687',
    unicode: 'U+1F1F3 U+1F1E8',
  },
  {
    code: 'NE',
    emoji: '🇳🇪',
    name: 'Niger',
    phoneCode: '227',
    unicode: 'U+1F1F3 U+1F1EA',
  },
  {
    code: 'NF',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
    phoneCode: '672',
    unicode: 'U+1F1F3 U+1F1EB',
  },
  {
    code: 'NG',
    emoji: '🇳🇬',
    name: 'Nigeria',
    phoneCode: '234',
    unicode: 'U+1F1F3 U+1F1EC',
  },
  {
    code: 'NI',
    emoji: '🇳🇮',
    name: 'Nicaragua',
    phoneCode: '505',
    unicode: 'U+1F1F3 U+1F1EE',
  },
  {
    code: 'NL',
    emoji: '🇳🇱',
    name: 'Netherlands',
    phoneCode: '31',
    unicode: 'U+1F1F3 U+1F1F1',
  },
  {
    code: 'NO',
    emoji: '🇳🇴',
    name: 'Norway',
    phoneCode: '47',
    unicode: 'U+1F1F3 U+1F1F4',
  },
  {
    code: 'NP',
    emoji: '🇳🇵',
    name: 'Nepal',
    phoneCode: '977',
    unicode: 'U+1F1F3 U+1F1F5',
  },
  {
    code: 'NR',
    emoji: '🇳🇷',
    name: 'Nauru',
    phoneCode: '674',
    unicode: 'U+1F1F3 U+1F1F7',
  },
  {
    code: 'NU',
    emoji: '🇳🇺',
    name: 'Niue',
    phoneCode: '683',
    unicode: 'U+1F1F3 U+1F1FA',
  },
  {
    code: 'NZ',
    emoji: '🇳🇿',
    name: 'New Zealand',
    phoneCode: '64',
    unicode: 'U+1F1F3 U+1F1FF',
  },
  {
    code: 'OM',
    emoji: '🇴🇲',
    name: 'Oman',
    phoneCode: '968',
    unicode: 'U+1F1F4 U+1F1F2',
  },
  {
    code: 'PA',
    emoji: '🇵🇦',
    name: 'Panama',
    phoneCode: '507',
    unicode: 'U+1F1F5 U+1F1E6',
  },
  {
    code: 'PE',
    emoji: '🇵🇪',
    name: 'Peru',
    phoneCode: '51',
    unicode: 'U+1F1F5 U+1F1EA',
  },
  {
    code: 'PF',
    emoji: '🇵🇫',
    name: 'French Polynesia',
    phoneCode: '689',
    unicode: 'U+1F1F5 U+1F1EB',
  },
  {
    code: 'PG',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    phoneCode: '675',
    unicode: 'U+1F1F5 U+1F1EC',
  },
  {
    code: 'PH',
    emoji: '🇵🇭',
    name: 'Philippines',
    phoneCode: '63',
    unicode: 'U+1F1F5 U+1F1ED',
  },
  {
    code: 'PK',
    emoji: '🇵🇰',
    name: 'Pakistan',
    phoneCode: '92',
    unicode: 'U+1F1F5 U+1F1F0',
  },
  {
    code: 'PL',
    emoji: '🇵🇱',
    name: 'Poland',
    phoneCode: '48',
    unicode: 'U+1F1F5 U+1F1F1',
  },
  {
    code: 'PM',
    emoji: '🇵🇲',
    name: 'St. Pierre & Miquelon',
    phoneCode: '508',
    unicode: 'U+1F1F5 U+1F1F2',
  },
  {
    code: 'PN',
    emoji: '🇵🇳',
    name: 'Pitcairn Islands',
    phoneCode: '870',
    unicode: 'U+1F1F5 U+1F1F3',
  },
  {
    code: 'PR',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
    phoneCode: '1-787 and 1-939',
    unicode: 'U+1F1F5 U+1F1F7',
  },
  {
    code: 'PS',
    emoji: '🇵🇸',
    name: 'Palestinian Territories',
    phoneCode: '970',
    unicode: 'U+1F1F5 U+1F1F8',
  },
  {
    code: 'PT',
    emoji: '🇵🇹',
    name: 'Portugal',
    phoneCode: '351',
    unicode: 'U+1F1F5 U+1F1F9',
  },
  {
    code: 'PW',
    emoji: '🇵🇼',
    name: 'Palau',
    phoneCode: '680',
    unicode: 'U+1F1F5 U+1F1FC',
  },
  {
    code: 'PY',
    emoji: '🇵🇾',
    name: 'Paraguay',
    phoneCode: '595',
    unicode: 'U+1F1F5 U+1F1FE',
  },
  {
    code: 'QA',
    emoji: '🇶🇦',
    name: 'Qatar',
    phoneCode: '974',
    unicode: 'U+1F1F6 U+1F1E6',
  },
  {
    code: 'RE',
    emoji: '🇷🇪',
    name: 'Réunion',
    phoneCode: '262',
    unicode: 'U+1F1F7 U+1F1EA',
  },
  {
    code: 'RO',
    emoji: '🇷🇴',
    name: 'Romania',
    phoneCode: '40',
    unicode: 'U+1F1F7 U+1F1F4',
  },
  {
    code: 'RS',
    emoji: '🇷🇸',
    name: 'Serbia',
    phoneCode: '381',
    unicode: 'U+1F1F7 U+1F1F8',
  },
  {
    code: 'RU',
    emoji: '🇷🇺',
    name: 'Russia',
    phoneCode: '7',
    unicode: 'U+1F1F7 U+1F1FA',
  },
  {
    code: 'RW',
    emoji: '🇷🇼',
    name: 'Rwanda',
    phoneCode: '250',
    unicode: 'U+1F1F7 U+1F1FC',
  },
  {
    code: 'SA',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
    phoneCode: '966',
    unicode: 'U+1F1F8 U+1F1E6',
  },
  {
    code: 'SB',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    phoneCode: '677',
    unicode: 'U+1F1F8 U+1F1E7',
  },
  {
    code: 'SC',
    emoji: '🇸🇨',
    name: 'Seychelles',
    phoneCode: '248',
    unicode: 'U+1F1F8 U+1F1E8',
  },
  {
    code: 'SD',
    emoji: '🇸🇩',
    name: 'Sudan',
    phoneCode: '249',
    unicode: 'U+1F1F8 U+1F1E9',
  },
  {
    code: 'SE',
    emoji: '🇸🇪',
    name: 'Sweden',
    phoneCode: '46',
    unicode: 'U+1F1F8 U+1F1EA',
  },
  {
    code: 'SG',
    emoji: '🇸🇬',
    name: 'Singapore',
    phoneCode: '65',
    unicode: 'U+1F1F8 U+1F1EC',
  },
  {
    code: 'SH',
    emoji: '🇸🇭',
    name: 'St. Helena',
    phoneCode: '290',
    unicode: 'U+1F1F8 U+1F1ED',
  },
  {
    code: 'SI',
    emoji: '🇸🇮',
    name: 'Slovenia',
    phoneCode: '386',
    unicode: 'U+1F1F8 U+1F1EE',
  },
  {
    code: 'SJ',
    emoji: '🇸🇯',
    name: 'Svalbard & Jan Mayen',
    phoneCode: '47',
    unicode: 'U+1F1F8 U+1F1EF',
  },
  {
    code: 'SK',
    emoji: '🇸🇰',
    name: 'Slovakia',
    phoneCode: '421',
    unicode: 'U+1F1F8 U+1F1F0',
  },
  {
    code: 'SL',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
    phoneCode: '232',
    unicode: 'U+1F1F8 U+1F1F1',
  },
  {
    code: 'SM',
    emoji: '🇸🇲',
    name: 'San Marino',
    phoneCode: '378',
    unicode: 'U+1F1F8 U+1F1F2',
  },
  {
    code: 'SN',
    emoji: '🇸🇳',
    name: 'Senegal',
    phoneCode: '221',
    unicode: 'U+1F1F8 U+1F1F3',
  },
  {
    code: 'SO',
    emoji: '🇸🇴',
    name: 'Somalia',
    phoneCode: '252',
    unicode: 'U+1F1F8 U+1F1F4',
  },
  {
    code: 'SR',
    emoji: '🇸🇷',
    name: 'Suriname',
    phoneCode: '597',
    unicode: 'U+1F1F8 U+1F1F7',
  },
  {
    code: 'SS',
    emoji: '🇸🇸',
    name: 'South Sudan',
    phoneCode: '211',
    unicode: 'U+1F1F8 U+1F1F8',
  },
  {
    code: 'ST',
    emoji: '🇸🇹',
    name: 'São Tomé & Príncipe',
    phoneCode: '239',
    unicode: 'U+1F1F8 U+1F1F9',
  },
  {
    code: 'SV',
    emoji: '🇸🇻',
    name: 'El Salvador',
    phoneCode: '503',
    unicode: 'U+1F1F8 U+1F1FB',
  },
  {
    code: 'SX',
    emoji: '🇸🇽',
    name: 'Sint Maarten',
    phoneCode: '599',
    unicode: 'U+1F1F8 U+1F1FD',
  },
  {
    code: 'SY',
    emoji: '🇸🇾',
    name: 'Syria',
    phoneCode: '963',
    unicode: 'U+1F1F8 U+1F1FE',
  },
  {
    code: 'SZ',
    emoji: '🇸🇿',
    name: 'Swaziland',
    phoneCode: '268',
    unicode: 'U+1F1F8 U+1F1FF',
  },
  {
    code: 'TA',
    emoji: '🇹🇦',
    name: 'Tristan da Cunha',
    phoneCode: '290',
    unicode: 'U+1F1F9 U+1F1E6',
  },
  {
    code: 'TC',
    emoji: '🇹🇨',
    name: 'Turks & Caicos Islands',
    phoneCode: '1-649',
    unicode: 'U+1F1F9 U+1F1E8',
  },
  {
    code: 'TD',
    emoji: '🇹🇩',
    name: 'Chad',
    phoneCode: '235',
    unicode: 'U+1F1F9 U+1F1E9',
  },
  {
    code: 'TG',
    emoji: '🇹🇬',
    name: 'Togo',
    phoneCode: '228',
    unicode: 'U+1F1F9 U+1F1EC',
  },
  {
    code: 'TH',
    emoji: '🇹🇭',
    name: 'Thailand',
    phoneCode: '66',
    unicode: 'U+1F1F9 U+1F1ED',
  },
  {
    code: 'TJ',
    emoji: '🇹🇯',
    name: 'Tajikistan',
    phoneCode: '992',
    unicode: 'U+1F1F9 U+1F1EF',
  },
  {
    code: 'TK',
    emoji: '🇹🇰',
    name: 'Tokelau',
    phoneCode: '690',
    unicode: 'U+1F1F9 U+1F1F0',
  },
  {
    code: 'TL',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
    phoneCode: '670',
    unicode: 'U+1F1F9 U+1F1F1',
  },
  {
    code: 'TM',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
    phoneCode: '993',
    unicode: 'U+1F1F9 U+1F1F2',
  },
  {
    code: 'TN',
    emoji: '🇹🇳',
    name: 'Tunisia',
    phoneCode: '216',
    unicode: 'U+1F1F9 U+1F1F3',
  },
  {
    code: 'TO',
    emoji: '🇹🇴',
    name: 'Tonga',
    phoneCode: '676',
    unicode: 'U+1F1F9 U+1F1F4',
  },
  {
    code: 'TR',
    emoji: '🇹🇷',
    name: 'Turkey',
    phoneCode: '90',
    unicode: 'U+1F1F9 U+1F1F7',
  },
  {
    code: 'TT',
    emoji: '🇹🇹',
    name: 'Trinidad & Tobago',
    phoneCode: '1-868',
    unicode: 'U+1F1F9 U+1F1F9',
  },
  {
    code: 'TV',
    emoji: '🇹🇻',
    name: 'Tuvalu',
    phoneCode: '688',
    unicode: 'U+1F1F9 U+1F1FB',
  },
  {
    code: 'TW',
    emoji: '🇹🇼',
    name: 'Taiwan',
    phoneCode: '886',
    unicode: 'U+1F1F9 U+1F1FC',
  },
  {
    code: 'TZ',
    emoji: '🇹🇿',
    name: 'Tanzania',
    phoneCode: '255',
    unicode: 'U+1F1F9 U+1F1FF',
  },
  {
    code: 'UA',
    emoji: '🇺🇦',
    name: 'Ukraine',
    phoneCode: '380',
    unicode: 'U+1F1FA U+1F1E6',
  },
  {
    code: 'UG',
    emoji: '🇺🇬',
    name: 'Uganda',
    phoneCode: '256',
    unicode: 'U+1F1FA U+1F1EC',
  },
  {
    code: 'UM',
    emoji: '🇺🇲',
    name: 'U.S. Outlying Islands',
    phoneCode: '1',
    unicode: 'U+1F1FA U+1F1F2',
  },
  {
    code: 'US',
    emoji: '🇺🇸',
    name: 'United States',
    phoneCode: '1',
    unicode: 'U+1F1FA U+1F1F8',
  },
  {
    code: 'UY',
    emoji: '🇺🇾',
    name: 'Uruguay',
    phoneCode: '598',
    unicode: 'U+1F1FA U+1F1FE',
  },
  {
    code: 'UZ',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
    phoneCode: '998',
    unicode: 'U+1F1FA U+1F1FF',
  },
  {
    code: 'VA',
    emoji: '🇻🇦',
    name: 'Vatican City',
    phoneCode: '379',
    unicode: 'U+1F1FB U+1F1E6',
  },
  {
    code: 'VC',
    emoji: '🇻🇨',
    name: 'St. Vincent & Grenadines',
    phoneCode: '1-784',
    unicode: 'U+1F1FB U+1F1E8',
  },
  {
    code: 'VE',
    emoji: '🇻🇪',
    name: 'Venezuela',
    phoneCode: '58',
    unicode: 'U+1F1FB U+1F1EA',
  },
  {
    code: 'VG',
    emoji: '🇻🇬',
    name: 'British Virgin Islands',
    phoneCode: '1-284',
    unicode: 'U+1F1FB U+1F1EC',
  },
  {
    code: 'VI',
    emoji: '🇻🇮',
    name: 'U.S. Virgin Islands',
    phoneCode: '1-340',
    unicode: 'U+1F1FB U+1F1EE',
  },
  {
    code: 'VN',
    emoji: '🇻🇳',
    name: 'Vietnam',
    phoneCode: '84',
    unicode: 'U+1F1FB U+1F1F3',
  },
  {
    code: 'VU',
    emoji: '🇻🇺',
    name: 'Vanuatu',
    phoneCode: '678',
    unicode: 'U+1F1FB U+1F1FA',
  },
  {
    code: 'WF',
    emoji: '🇼🇫',
    name: 'Wallis & Futuna',
    phoneCode: '681',
    unicode: 'U+1F1FC U+1F1EB',
  },
  {
    code: 'WS',
    emoji: '🇼🇸',
    name: 'Samoa',
    phoneCode: '685',
    unicode: 'U+1F1FC U+1F1F8',
  },
  {
    code: 'XK',
    emoji: '🇽🇰',
    name: 'Kosovo',
    phoneCode: '383',
    unicode: 'U+1F1FD U+1F1F0',
  },
  {
    code: 'YE',
    emoji: '🇾🇪',
    name: 'Yemen',
    phoneCode: '967',
    unicode: 'U+1F1FE U+1F1EA',
  },
  {
    code: 'YT',
    emoji: '🇾🇹',
    name: 'Mayotte',
    phoneCode: '262',
    unicode: 'U+1F1FE U+1F1F9',
  },
  {
    code: 'ZA',
    emoji: '🇿🇦',
    name: 'South Africa',
    phoneCode: '27',
    unicode: 'U+1F1FF U+1F1E6',
  },
  {
    code: 'ZM',
    emoji: '🇿🇲',
    name: 'Zambia',
    phoneCode: '260',
    unicode: 'U+1F1FF U+1F1F2',
  },
  {
    code: 'ZW',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
    phoneCode: '263',
    unicode: 'U+1F1FF U+1F1FC',
  },
];

export const TIMEZONES: TimeZone[] = [
  {
    value: 'Dateline Standard Time',
    abbr: 'DST',
    offset: -12,
    isdst: false,
    text: '(UTC-12:00) International Date Line West',
    utc: ['Etc/GMT+12'],
  },
  {
    value: 'UTC-11',
    abbr: 'U',
    offset: -11,
    isdst: false,
    text: '(UTC-11:00) Coordinated Universal Time-11',
    utc: ['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
  },
  {
    value: 'Hawaiian Standard Time',
    abbr: 'HST',
    offset: -10,
    isdst: false,
    text: '(UTC-10:00) Hawaii',
    utc: [
      'Etc/GMT+10',
      'Pacific/Honolulu',
      'Pacific/Johnston',
      'Pacific/Rarotonga',
      'Pacific/Tahiti',
    ],
  },
  {
    value: 'Alaskan Standard Time',
    abbr: 'AKDT',
    offset: -9,
    isdst: true,
    text: '(UTC-09:00) Alaska',
    utc: [
      'America/Anchorage',
      'America/Juneau',
      'America/Nome',
      'America/Sitka',
      'America/Yakutat',
    ],
  },
  {
    value: 'Pacific Standard Time',
    abbr: 'PST',
    offset: -8,
    isdst: false,
    text: '(UTC-08:00) Pacific Time (US & Canada)',
    utc: [
      'America/Dawson',
      'America/Los_Angeles',
      'America/Tijuana',
      'America/Vancouver',
      'America/Whitehorse',
      'PST8PDT',
    ],
  },
  {
    value: 'Pacific Standard Time (Mexico)',
    abbr: 'PDT',
    offset: -8,
    isdst: true,
    text: '(UTC-08:00) Baja California',
    utc: ['America/Santa_Isabel'],
  },
  {
    value: 'Pacific Daylight Time',
    abbr: 'PDT',
    offset: -7,
    isdst: true,
    text: '(UTC-07:00) Pacific Time (US & Canada)',
    utc: [
      'America/Dawson',
      'America/Los_Angeles',
      'America/Tijuana',
      'America/Vancouver',
      'America/Whitehorse',
    ],
  },
  {
    value: 'US Mountain Standard Time',
    abbr: 'UMST',
    offset: -7,
    isdst: false,
    text: '(UTC-07:00) Arizona',
    utc: [
      'America/Creston',
      'America/Dawson_Creek',
      'America/Hermosillo',
      'America/Phoenix',
      'Etc/GMT+7',
    ],
  },
  {
    value: 'Mountain Standard Time (Mexico)',
    abbr: 'MDT',
    offset: -7,
    isdst: true,
    text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    utc: ['America/Chihuahua', 'America/Mazatlan'],
  },
  {
    value: 'Mountain Standard Time',
    abbr: 'MDT',
    offset: -7,
    isdst: true,
    text: '(UTC-07:00) Mountain Time (US & Canada)',
    utc: [
      'America/Boise',
      'America/Cambridge_Bay',
      'America/Denver',
      'America/Edmonton',
      'America/Inuvik',
      'America/Ojinaga',
      'America/Yellowknife',
      'MST7MDT',
    ],
  },
  {
    value: 'Central America Standard Time',
    abbr: 'CAST',
    offset: -6,
    isdst: false,
    text: '(UTC-06:00) Central America',
    utc: [
      'America/Belize',
      'America/Costa_Rica',
      'America/El_Salvador',
      'America/Guatemala',
      'America/Managua',
      'America/Tegucigalpa',
      'Etc/GMT+6',
      'Pacific/Galapagos',
    ],
  },
  {
    value: 'Central Standard Time',
    abbr: 'CDT',
    offset: -6,
    isdst: true,
    text: '(UTC-06:00) Central Time (US & Canada)',
    utc: [
      'America/Chicago',
      'America/Indiana/Knox',
      'America/Indiana/Tell_City',
      'America/Matamoros',
      'America/Menominee',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Resolute',
      'America/Winnipeg',
      'CST6CDT',
    ],
  },
  {
    value: 'Central Standard Time (Mexico)',
    abbr: 'CDT',
    offset: -6,
    isdst: true,
    text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    utc: [
      'America/Bahia_Banderas',
      'America/Cancun',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
    ],
  },
  {
    value: 'Canada Central Standard Time',
    abbr: 'CCST',
    offset: -6,
    isdst: false,
    text: '(UTC-06:00) Saskatchewan',
    utc: ['America/Regina', 'America/Swift_Current'],
  },
  {
    value: 'SA Pacific Standard Time',
    abbr: 'SPST',
    offset: -5,
    isdst: false,
    text: '(UTC-05:00) Bogota, Lima, Quito',
    utc: [
      'America/Bogota',
      'America/Cayman',
      'America/Coral_Harbour',
      'America/Eirunepe',
      'America/Guayaquil',
      'America/Jamaica',
      'America/Lima',
      'America/Panama',
      'America/Rio_Branco',
      'Etc/GMT+5',
    ],
  },
  {
    value: 'Eastern Standard Time',
    abbr: 'EDT',
    offset: -5,
    isdst: true,
    text: '(UTC-05:00) Eastern Time (US & Canada)',
    utc: [
      'America/Detroit',
      'America/Havana',
      'America/Indiana/Petersburg',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/New_York',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
      'EST5EDT',
    ],
  },
  {
    value: 'US Eastern Standard Time',
    abbr: 'UEDT',
    offset: -5,
    isdst: true,
    text: '(UTC-05:00) Indiana (East)',
    utc: [
      'America/Indiana/Marengo',
      'America/Indiana/Vevay',
      'America/Indianapolis',
    ],
  },
  {
    value: 'Venezuela Standard Time',
    abbr: 'VST',
    offset: -4.5,
    isdst: false,
    text: '(UTC-04:30) Caracas',
    utc: ['America/Caracas'],
  },
  {
    value: 'Paraguay Standard Time',
    abbr: 'PYT',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Asuncion',
    utc: ['America/Asuncion'],
  },
  {
    value: 'Atlantic Standard Time',
    abbr: 'ADT',
    offset: -4,
    isdst: true,
    text: '(UTC-04:00) Atlantic Time (Canada)',
    utc: [
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Moncton',
      'America/Thule',
      'Atlantic/Bermuda',
    ],
  },
  {
    value: 'Central Brazilian Standard Time',
    abbr: 'CBST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Cuiaba',
    utc: ['America/Campo_Grande', 'America/Cuiaba'],
  },
  {
    value: 'SA Western Standard Time',
    abbr: 'SWST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    utc: [
      'America/Anguilla',
      'America/Antigua',
      'America/Aruba',
      'America/Barbados',
      'America/Blanc-Sablon',
      'America/Boa_Vista',
      'America/Curacao',
      'America/Dominica',
      'America/Grand_Turk',
      'America/Grenada',
      'America/Guadeloupe',
      'America/Guyana',
      'America/Kralendijk',
      'America/La_Paz',
      'America/Lower_Princes',
      'America/Manaus',
      'America/Marigot',
      'America/Martinique',
      'America/Montserrat',
      'America/Port_of_Spain',
      'America/Porto_Velho',
      'America/Puerto_Rico',
      'America/Santo_Domingo',
      'America/St_Barthelemy',
      'America/St_Kitts',
      'America/St_Lucia',
      'America/St_Thomas',
      'America/St_Vincent',
      'America/Tortola',
      'Etc/GMT+4',
    ],
  },
  {
    value: 'Pacific SA Standard Time',
    abbr: 'PSST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Santiago',
    utc: ['America/Santiago', 'Antarctica/Palmer'],
  },
  {
    value: 'Newfoundland Standard Time',
    abbr: 'NDT',
    offset: -3.5,
    isdst: true,
    text: '(UTC-03:30) Newfoundland',
    utc: ['America/St_Johns'],
  },
  {
    value: 'E. South America Standard Time',
    abbr: 'ESAST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Brasilia',
    utc: ['America/Sao_Paulo'],
  },
  {
    value: 'Argentina Standard Time',
    abbr: 'AST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Buenos Aires',
    utc: [
      'America/Argentina/La_Rioja',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'America/Buenos_Aires',
      'America/Catamarca',
      'America/Cordoba',
      'America/Jujuy',
      'America/Mendoza',
    ],
  },
  {
    value: 'SA Eastern Standard Time',
    abbr: 'SEST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Cayenne, Fortaleza',
    utc: [
      'America/Araguaina',
      'America/Belem',
      'America/Cayenne',
      'America/Fortaleza',
      'America/Maceio',
      'America/Paramaribo',
      'America/Recife',
      'America/Santarem',
      'Antarctica/Rothera',
      'Atlantic/Stanley',
      'Etc/GMT+3',
    ],
  },
  {
    value: 'Greenland Standard Time',
    abbr: 'GDT',
    offset: -3,
    isdst: true,
    text: '(UTC-03:00) Greenland',
    utc: ['America/Godthab'],
  },
  {
    value: 'Montevideo Standard Time',
    abbr: 'MST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Montevideo',
    utc: ['America/Montevideo'],
  },
  {
    value: 'Bahia Standard Time',
    abbr: 'BST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Salvador',
    utc: ['America/Bahia'],
  },
  {
    value: 'UTC-02',
    abbr: 'U',
    offset: -2,
    isdst: false,
    text: '(UTC-02:00) Coordinated Universal Time-02',
    utc: ['America/Noronha', 'Atlantic/South_Georgia', 'Etc/GMT+2'],
  },
  {
    value: 'Mid-Atlantic Standard Time',
    abbr: 'MDT',
    offset: -2,
    isdst: true,
    text: '(UTC-02:00) Mid-Atlantic - Old',
    utc: [],
  },
  {
    value: 'Azores Standard Time',
    abbr: 'ADT',
    offset: -1,
    isdst: true,
    text: '(UTC-01:00) Azores',
    utc: ['America/Scoresbysund', 'Atlantic/Azores'],
  },
  {
    value: 'Cape Verde Standard Time',
    abbr: 'CVST',
    offset: -1,
    isdst: false,
    text: '(UTC-01:00) Cape Verde Is.',
    utc: ['Atlantic/Cape_Verde', 'Etc/GMT+1'],
  },
  {
    value: 'Morocco Standard Time',
    abbr: 'MDT',
    offset: 0,
    isdst: true,
    text: '(UTC) Casablanca',
    utc: ['Africa/Casablanca', 'Africa/El_Aaiun'],
  },
  {
    value: 'UTC',
    abbr: 'UTC',
    offset: 0,
    isdst: false,
    text: '(UTC) Coordinated Universal Time',
    utc: ['America/Danmarkshavn', 'Etc/GMT'],
  },
  {
    value: 'GMT Standard Time',
    abbr: 'GMT',
    offset: 0,
    isdst: false,
    text: '(UTC) Edinburgh, London',
    utc: [
      'Europe/Isle_of_Man',
      'Europe/Guernsey',
      'Europe/Jersey',
      'Europe/London',
    ],
  },
  {
    value: 'GMT Standard Time',
    abbr: 'GDT',
    offset: 0,
    isdst: true,
    text: '(UTC) Dublin, Lisbon',
    utc: [
      'Atlantic/Canary',
      'Atlantic/Faeroe',
      'Atlantic/Madeira',
      'Europe/Dublin',
      'Europe/Lisbon',
    ],
  },
  {
    value: 'Greenwich Standard Time',
    abbr: 'GST',
    offset: 0,
    isdst: false,
    text: '(UTC) Monrovia, Reykjavik',
    utc: [
      'Africa/Abidjan',
      'Africa/Accra',
      'Africa/Bamako',
      'Africa/Banjul',
      'Africa/Bissau',
      'Africa/Conakry',
      'Africa/Dakar',
      'Africa/Freetown',
      'Africa/Lome',
      'Africa/Monrovia',
      'Africa/Nouakchott',
      'Africa/Ouagadougou',
      'Africa/Sao_Tome',
      'Atlantic/Reykjavik',
      'Atlantic/St_Helena',
    ],
  },
  {
    value: 'British Summer Time',
    abbr: 'BST',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Edinburgh, London',
    utc: [
      'Europe/Isle_of_Man',
      'Europe/Guernsey',
      'Europe/Jersey',
      'Europe/London',
    ],
  },
  {
    value: 'W. Europe Standard Time',
    abbr: 'WEDT',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    utc: [
      'Arctic/Longyearbyen',
      'Europe/Amsterdam',
      'Europe/Andorra',
      'Europe/Berlin',
      'Europe/Busingen',
      'Europe/Gibraltar',
      'Europe/Luxembourg',
      'Europe/Malta',
      'Europe/Monaco',
      'Europe/Oslo',
      'Europe/Rome',
      'Europe/San_Marino',
      'Europe/Stockholm',
      'Europe/Vaduz',
      'Europe/Vatican',
      'Europe/Vienna',
      'Europe/Zurich',
    ],
  },
  {
    value: 'Central Europe Standard Time',
    abbr: 'CEDT',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    utc: [
      'Europe/Belgrade',
      'Europe/Bratislava',
      'Europe/Budapest',
      'Europe/Ljubljana',
      'Europe/Podgorica',
      'Europe/Prague',
      'Europe/Tirane',
    ],
  },
  {
    value: 'Romance Standard Time',
    abbr: 'RDT',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    utc: [
      'Africa/Ceuta',
      'Europe/Brussels',
      'Europe/Copenhagen',
      'Europe/Madrid',
      'Europe/Paris',
    ],
  },
  {
    value: 'Central European Standard Time',
    abbr: 'CEDT',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    utc: ['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb'],
  },
  {
    value: 'W. Central Africa Standard Time',
    abbr: 'WCAST',
    offset: 1,
    isdst: false,
    text: '(UTC+01:00) West Central Africa',
    utc: [
      'Africa/Algiers',
      'Africa/Bangui',
      'Africa/Brazzaville',
      'Africa/Douala',
      'Africa/Kinshasa',
      'Africa/Lagos',
      'Africa/Libreville',
      'Africa/Luanda',
      'Africa/Malabo',
      'Africa/Ndjamena',
      'Africa/Niamey',
      'Africa/Porto-Novo',
      'Africa/Tunis',
      'Etc/GMT-1',
    ],
  },
  {
    value: 'Namibia Standard Time',
    abbr: 'NST',
    offset: 1,
    isdst: false,
    text: '(UTC+01:00) Windhoek',
    utc: ['Africa/Windhoek'],
  },
  {
    value: 'GTB Standard Time',
    abbr: 'GDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) Athens, Bucharest',
    utc: [
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
    ],
  },
  {
    value: 'Middle East Standard Time',
    abbr: 'MEDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) Beirut',
    utc: ['Asia/Beirut'],
  },
  {
    value: 'Egypt Standard Time',
    abbr: 'EST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Cairo',
    utc: ['Africa/Cairo'],
  },
  {
    value: 'Syria Standard Time',
    abbr: 'SDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) Damascus',
    utc: ['Asia/Damascus'],
  },
  {
    value: 'E. Europe Standard Time',
    abbr: 'EEDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) E. Europe',
    utc: [
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
      'Europe/Helsinki',
      'Europe/Kiev',
      'Europe/Mariehamn',
      'Europe/Nicosia',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhgorod',
      'Europe/Vilnius',
      'Europe/Zaporozhye',
    ],
  },
  {
    value: 'South Africa Standard Time',
    abbr: 'SAST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Harare, Pretoria',
    utc: [
      'Africa/Blantyre',
      'Africa/Bujumbura',
      'Africa/Gaborone',
      'Africa/Harare',
      'Africa/Johannesburg',
      'Africa/Kigali',
      'Africa/Lubumbashi',
      'Africa/Lusaka',
      'Africa/Maputo',
      'Africa/Maseru',
      'Africa/Mbabane',
      'Etc/GMT-2',
    ],
  },
  {
    value: 'FLE Standard Time',
    abbr: 'FDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    utc: [
      'Europe/Helsinki',
      'Europe/Kiev',
      'Europe/Mariehamn',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhgorod',
      'Europe/Vilnius',
      'Europe/Zaporozhye',
    ],
  },
  {
    value: 'Israel Standard Time',
    abbr: 'JDT',
    offset: 2,
    isdst: true,
    text: '(UTC+02:00) Jerusalem',
    utc: ['Asia/Jerusalem'],
  },
  {
    value: 'Turkey Standard Time',
    abbr: 'TDT',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Istanbul',
    utc: ['Europe/Istanbul'],
  },

  {
    value: 'Libya Standard Time',
    abbr: 'LST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Tripoli',
    utc: ['Africa/Tripoli'],
  },
  {
    value: 'Kaliningrad Standard Time',
    abbr: 'KST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Kaliningrad',
    utc: ['Europe/Kaliningrad'],
  },
  {
    value: 'Jordan Standard Time',
    abbr: 'JST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Amman',
    utc: ['Asia/Amman'],
  },
  {
    value: 'Arabic Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Baghdad',
    utc: ['Asia/Baghdad'],
  },

  {
    value: 'Arab Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Kuwait, Riyadh',
    utc: [
      'Asia/Aden',
      'Asia/Bahrain',
      'Asia/Kuwait',
      'Asia/Qatar',
      'Asia/Riyadh',
    ],
  },
  {
    value: 'E. Africa Standard Time',
    abbr: 'EAST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Nairobi',
    utc: [
      'Africa/Addis_Ababa',
      'Africa/Asmera',
      'Africa/Dar_es_Salaam',
      'Africa/Djibouti',
      'Africa/Juba',
      'Africa/Kampala',
      'Africa/Khartoum',
      'Africa/Mogadishu',
      'Africa/Nairobi',
      'Antarctica/Syowa',
      'Etc/GMT-3',
      'Indian/Antananarivo',
      'Indian/Comoro',
      'Indian/Mayotte',
    ],
  },
  {
    value: 'Moscow Standard Time',
    abbr: 'MSK',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
    utc: [
      'Europe/Kirov',
      'Europe/Moscow',
      'Europe/Simferopol',
      'Europe/Volgograd',
      'Europe/Minsk',
    ],
  },
  {
    value: 'Iran Standard Time',
    abbr: 'IDT',
    offset: 3.5,
    isdst: true,
    text: '(UTC+03:30) Tehran',
    utc: ['Asia/Tehran'],
  },
  {
    value: 'Samara Time',
    abbr: 'SAMT',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
    utc: ['Europe/Astrakhan', 'Europe/Samara', 'Europe/Ulyanovsk'],
  },

  {
    value: 'Arabian Standard Time',
    abbr: 'AST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Abu Dhabi, Muscat',
    utc: ['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4'],
  },
  {
    value: 'Azerbaijan Standard Time',
    abbr: 'ADT',
    offset: 4,
    isdst: true,
    text: '(UTC+04:00) Baku',
    utc: ['Asia/Baku'],
  },
  {
    value: 'Mauritius Standard Time',
    abbr: 'MST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Port Louis',
    utc: ['Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion'],
  },
  {
    value: 'Georgian Standard Time',
    abbr: 'GET',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Tbilisi',
    utc: ['Asia/Tbilisi'],
  },
  {
    value: 'Caucasus Standard Time',
    abbr: 'CST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Yerevan',
    utc: ['Asia/Yerevan'],
  },
  {
    value: 'Afghanistan Standard Time',
    abbr: 'AST',
    offset: 4.5,
    isdst: false,
    text: '(UTC+04:30) Kabul',
    utc: ['Asia/Kabul'],
  },
  {
    value: 'West Asia Standard Time',
    abbr: 'WAST',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Ashgabat, Tashkent',
    utc: [
      'Antarctica/Mawson',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Ashgabat',
      'Asia/Dushanbe',
      'Asia/Oral',
      'Asia/Samarkand',
      'Asia/Tashkent',
      'Etc/GMT-5',
      'Indian/Kerguelen',
      'Indian/Maldives',
    ],
  },
  {
    value: 'Yekaterinburg Time',
    abbr: 'YEKT',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Yekaterinburg',
    utc: ['Asia/Yekaterinburg'],
  },
  {
    value: 'Pakistan Standard Time',
    abbr: 'PKT',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Islamabad, Karachi',
    utc: ['Asia/Karachi'],
  },
  {
    value: 'India Standard Time',
    abbr: 'IST',
    offset: 5.5,
    isdst: false,
    text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    utc: ['Asia/Kolkata'],
  },
  {
    value: 'Sri Lanka Standard Time',
    abbr: 'SLST',
    offset: 5.5,
    isdst: false,
    text: '(UTC+05:30) Sri Jayawardenepura',
    utc: ['Asia/Colombo'],
  },
  {
    value: 'Nepal Standard Time',
    abbr: 'NST',
    offset: 5.75,
    isdst: false,
    text: '(UTC+05:45) Kathmandu',
    utc: ['Asia/Kathmandu'],
  },
  {
    value: 'Central Asia Standard Time',
    abbr: 'CAST',
    offset: 6,
    isdst: false,
    text: '(UTC+06:00) Nur-Sultan (Astana)',
    utc: [
      'Antarctica/Vostok',
      'Asia/Almaty',
      'Asia/Bishkek',
      'Asia/Qyzylorda',
      'Asia/Urumqi',
      'Etc/GMT-6',
      'Indian/Chagos',
    ],
  },
  {
    value: 'Bangladesh Standard Time',
    abbr: 'BST',
    offset: 6,
    isdst: false,
    text: '(UTC+06:00) Dhaka',
    utc: ['Asia/Dhaka', 'Asia/Thimphu'],
  },
  {
    value: 'Myanmar Standard Time',
    abbr: 'MST',
    offset: 6.5,
    isdst: false,
    text: '(UTC+06:30) Yangon (Rangoon)',
    utc: ['Asia/Rangoon', 'Indian/Cocos'],
  },
  {
    value: 'SE Asia Standard Time',
    abbr: 'SAST',
    offset: 7,
    isdst: false,
    text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    utc: [
      'Antarctica/Davis',
      'Asia/Bangkok',
      'Asia/Hovd',
      'Asia/Jakarta',
      'Asia/Phnom_Penh',
      'Asia/Pontianak',
      'Asia/Saigon',
      'Asia/Vientiane',
      'Etc/GMT-7',
      'Indian/Christmas',
    ],
  },
  {
    value: 'N. Central Asia Standard Time',
    abbr: 'NCAST',
    offset: 7,
    isdst: false,
    text: '(UTC+07:00) Novosibirsk',
    utc: ['Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk'],
  },
  {
    value: 'China Standard Time',
    abbr: 'CST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    utc: ['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai'],
  },
  {
    value: 'North Asia Standard Time',
    abbr: 'NAST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Krasnoyarsk',
    utc: ['Asia/Krasnoyarsk'],
  },
  {
    value: 'Singapore Standard Time',
    abbr: 'MPST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Kuala Lumpur, Singapore',
    utc: [
      'Asia/Brunei',
      'Asia/Kuala_Lumpur',
      'Asia/Kuching',
      'Asia/Makassar',
      'Asia/Manila',
      'Asia/Singapore',
      'Etc/GMT-8',
    ],
  },
  {
    value: 'W. Australia Standard Time',
    abbr: 'WAST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Perth',
    utc: ['Antarctica/Casey', 'Australia/Perth'],
  },
  {
    value: 'Taipei Standard Time',
    abbr: 'TST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Taipei',
    utc: ['Asia/Taipei'],
  },
  {
    value: 'Ulaanbaatar Standard Time',
    abbr: 'UST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Ulaanbaatar',
    utc: ['Asia/Choibalsan', 'Asia/Ulaanbaatar'],
  },
  {
    value: 'North Asia East Standard Time',
    abbr: 'NAEST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Irkutsk',
    utc: ['Asia/Irkutsk'],
  },
  {
    value: 'Japan Standard Time',
    abbr: 'JST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    utc: [
      'Asia/Dili',
      'Asia/Jayapura',
      'Asia/Tokyo',
      'Etc/GMT-9',
      'Pacific/Palau',
    ],
  },
  {
    value: 'Korea Standard Time',
    abbr: 'KST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Seoul',
    utc: ['Asia/Pyongyang', 'Asia/Seoul'],
  },
  {
    value: 'Yakutsk Standard Time',
    abbr: 'YST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Yakutsk',
    utc: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Yakutsk'],
  },
  {
    value: 'Cen. Australia Standard Time',
    abbr: 'CAST',
    offset: 9.5,
    isdst: false,
    text: '(UTC+09:30) Adelaide',
    utc: ['Australia/Adelaide', 'Australia/Broken_Hill'],
  },
  {
    value: 'AUS Central Standard Time',
    abbr: 'ACST',
    offset: 9.5,
    isdst: false,
    text: '(UTC+09:30) Darwin',
    utc: ['Australia/Darwin'],
  },
  {
    value: 'E. Australia Standard Time',
    abbr: 'EAST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Brisbane',
    utc: ['Australia/Brisbane', 'Australia/Lindeman'],
  },
  {
    value: 'AUS Eastern Standard Time',
    abbr: 'AEST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Canberra, Melbourne, Sydney',
    utc: ['Australia/Melbourne', 'Australia/Sydney'],
  },
  {
    value: 'West Pacific Standard Time',
    abbr: 'WPST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Guam, Port Moresby',
    utc: [
      'Antarctica/DumontDUrville',
      'Etc/GMT-10',
      'Pacific/Guam',
      'Pacific/Port_Moresby',
      'Pacific/Saipan',
      'Pacific/Truk',
    ],
  },
  {
    value: 'Tasmania Standard Time',
    abbr: 'TST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Hobart',
    utc: ['Australia/Currie', 'Australia/Hobart'],
  },
  {
    value: 'Central Pacific Standard Time',
    abbr: 'CPST',
    offset: 11,
    isdst: false,
    text: '(UTC+11:00) Solomon Is., New Caledonia',
    utc: [
      'Antarctica/Macquarie',
      'Etc/GMT-11',
      'Pacific/Efate',
      'Pacific/Guadalcanal',
      'Pacific/Kosrae',
      'Pacific/Noumea',
      'Pacific/Ponape',
    ],
  },
  {
    value: 'Vladivostok Standard Time',
    abbr: 'VST',
    offset: 11,
    isdst: false,
    text: '(UTC+11:00) Vladivostok',
    utc: ['Asia/Sakhalin', 'Asia/Ust-Nera', 'Asia/Vladivostok'],
  },
  {
    value: 'New Zealand Standard Time',
    abbr: 'NZST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Auckland, Wellington',
    utc: ['Antarctica/McMurdo', 'Pacific/Auckland'],
  },
  {
    value: 'UTC+12',
    abbr: 'U',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Coordinated Universal Time+12',
    utc: [
      'Etc/GMT-12',
      'Pacific/Funafuti',
      'Pacific/Kwajalein',
      'Pacific/Majuro',
      'Pacific/Nauru',
      'Pacific/Tarawa',
      'Pacific/Wake',
      'Pacific/Wallis',
    ],
  },
  {
    value: 'Fiji Standard Time',
    abbr: 'FST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Fiji',
    utc: ['Pacific/Fiji'],
  },
  {
    value: 'Magadan Standard Time',
    abbr: 'MST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Magadan',
    utc: [
      'Asia/Anadyr',
      'Asia/Kamchatka',
      'Asia/Magadan',
      'Asia/Srednekolymsk',
    ],
  },
  {
    value: 'Kamchatka Standard Time',
    abbr: 'KDT',
    offset: 12,
    isdst: true,
    text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    utc: ['Asia/Kamchatka'],
  },
  {
    value: 'Tonga Standard Time',
    abbr: 'TST',
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Nuku'alofa",
    utc: [
      'Etc/GMT-13',
      'Pacific/Enderbury',
      'Pacific/Fakaofo',
      'Pacific/Tongatapu',
    ],
  },
  {
    value: 'Samoa Standard Time',
    abbr: 'SST',
    offset: 13,
    isdst: false,
    text: '(UTC+13:00) Samoa',
    utc: ['Pacific/Apia'],
  },
];
