variables:
  RELEASE_FOLDER: 'dist\didex-exchange'
  DEPLOY_FOLDER: 'c:\sites\didex.userClient'

stages:
  # - build
  # - test
  - deploy
  - deliver

# build_job:
#   stage: build
#   only:
#     - tags
#   script:
#     - npm i
#     - npm run build-dev
# test_job:
#   stage: test
#   only:
#     - tags
#   script:
#     - dir

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - npm i
    - npm run build-dev
    - xcopy  /S /Q /Y /F .\dist\didex-exchange C:\sites\didex.userClient\
    
deliver_job:
  stage: deliver
  only:
    - tags
  script:
    - npm i
    - npm run build
    - xcopy  /S /Q /Y /F .\dist\didex-exchange C:\sites-prod\didex.userClient\
  # dependencies:
  #   - build_job
  #   - test_job
